openapi: 3.0.0
info:
  version: 1.0.0
  title: JSON Placeholder API 中文版
  description: See https://jsonplaceholder.typicode.com/
paths:
  /posts:
    get:
      description: 所有的貼文
      tags:
        - Posts
      operationId: getPosts
      responses:
        "200":
          description: 呼叫成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostsList"
  /posts/{id}:
    get:
      description: 根據 id 回傳貼文
      tags:
        - Posts
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          description: User 的 id
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: 呼叫成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "403":
          description: 你沒有權限
        "404":
          description: 沒有對應的貼文
        "500":
          description: 伺服器錯誤
components:
  schemas:
    PostsList:
      type: array
      items:
        $ref: "#/components/schemas/Post"
    Post:
      type: object
      required:
        - id
        - userId
        - title
        - completed
      properties:
        id:
          type: integer
        userId:
          type: integer
        title:
          type: string
        completed:
          type: string
